export const SHOW_ADD_TODO_DIALOG = "SHOW_ADD_TODO_DIALOG";
export const HIDE_ADD_TODO_DIALOG = "HIDE_ADD_TODO_DIALOG";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";